services:
  - type: web
    name: healthcare-msd
    env: node
    plan: free
    buildCommand: npm install && npm run build:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://tchakri_db_user:chakri2006@cluster0.t82bevd.mongodb.net/healthsystem
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here_12345
      - key: JWT_EXPIRE
        value: 7d
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        value: 231fa04f98@gmail.com
      - key: EMAIL_PASS
        value: xdcnfgvbiegtcxl